Repository LayerManager/layman, pull requests merged in 2020-11, with the labels that each got.

#122 Test of dynamic methods
  README.md
  doc/dependencies.md
  src/layman/util_test.py
Labels: code management

#126 Improve flask test client methods and usage in tests.
  src/layman/authn/oauth2_test.py
  src/layman/authz/read_everyone_write_owner_auth2_test.py
  src/layman/authz/read_everyone_write_owner_test.py
  src/layman/common/geoserver/__init__.py
  src/layman/layer/micka/csw_test.py
  src/layman/layer/rest_test.py
  src/layman/map/rest_test.py
  test/flask_client.py
Labels: code management

#129 Create process client decorator, improve publish/patch/delete map/layer methods for process client.
  test/process.py
  test/process_client.py
Labels: code management

#134 Test and repair url in get.maps
  CHANGELOG.md
  src/layman/map/rest_maps.py
  src/layman/map/rest_maps_test.py
Labels: bug

#131 Access rights are stored and loaded with REST endpoints
  src/layman/authz/util.py
  src/layman/common/prime_db_schema/publications.py
  src/layman/common/prime_db_schema/publications_test.py
  src/layman/common/prime_db_schema/rights.py
  src/layman/common/prime_db_schema/schema_initialization.py
  src/layman/common/prime_db_schema/users_test.py
  src/layman/common/prime_db_schema/workspaces_test.py
  src/layman/layer/prime_db_schema/table.py
  src/layman/layer/rest_layer.py
  src/layman/layer/rest_layers.py
  src/layman/layer/rest_layers_test.py
  src/layman/map/prime_db_schema/table.py
  src/layman/map/rest_map.py
  src/layman/map/rest_maps.py
  src/layman/map/rest_maps_test.py
  test/process_client.py
Labels: enhancement

#135 Access rights are tested against axioms
  src/layman/common/prime_db_schema/publications.py
  src/layman/common/prime_db_schema/publications_test.py
  src/layman/error_list.py
  src/layman/gs_wfs_proxy_test.py
Labels: enhancement

#136 Add access_rights into documentation and changelog.
  CHANGELOG.md
  doc/models.md
  doc/rest.md
Labels: enhancement

#138 Repair and add tests
  src/layman/__init__.py
  src/layman/authz_geoserver_test.py
  src/layman/celery_test.py
  src/layman/common/geoserver/__init__.py
  src/layman/common/prime_db_schema/migrate_test.py
  src/layman/common/prime_db_schema/publications.py
  src/layman/common/prime_db_schema/publications_test.py
  src/layman/common/prime_db_schema/users.py
  src/layman/gs_wfs_proxy_test.py
  src/layman/layer/geoserver/__init__.py
  src/layman/layer/geoserver/wfs.py
  src/layman/layer/prime_db_schema/rest_patch_layer_test.py
  src/layman/layer/rest_layer_patch_test.py
  src/layman/layer/rest_layer_style_test.py
  src/layman/user/rest_users_test.py
  src/layman/util_test.py
  test/flask_client.py
  test/process.py
  test/process_client.py
Labels: enhancement

#140 Test env. variables for using public workspaces
  src/layman/authz/authz_test.py
  src/layman/layer/rest_layer_patch_test.py
  test/process.py
  test/process_client.py
Labels: enhancement

#146 GeoServer HTTP header filter chain is used also for wms and ows
  src/geoserver/authn.py
  src/layman_settings.py
  src/setup_gs_auth.py
Labels: enhancement

#152 Replace old authorization modules with single authorization
  .env.demo
  .env.dev
  .env.test
  CHANGELOG.md
  doc/data-storage.md
  doc/env-settings.md
  doc/models.md
  doc/rest.md
  doc/security.md
  src/layman/authn/oauth2_test.py
  src/layman/authz/__init__.py
  src/layman/authz/authz_test.py
  src/layman/authz/read_everyone_write_everyone.py
  src/layman/authz/read_everyone_write_owner.py
  src/layman/authz/read_everyone_write_owner_auth2_test.py
  src/layman/authz/read_everyone_write_owner_test.py
  src/layman/authz/util.py
  src/layman/authz_geoserver_test.py
  src/layman/common/geoserver/__init__.py
  src/layman/common/prime_db_schema/publications_test.py
  src/layman/common/rest.py
  src/layman/common/rest_test.py
  src/layman/gs_wfs_proxy.py
  src/layman/gs_wfs_proxy_test.py
  src/layman/layer/geoserver/__init__.py
  src/layman/layer/geoserver/tasks.py
  src/layman/layer/geoserver/wfs.py
  src/layman/layer/rest_layer.py
  src/layman/layer/rest_layer_chunk.py
  src/layman/layer/rest_layer_metadata_comparison.py
  src/layman/layer/rest_layer_patch_test.py
  src/layman/layer/rest_layer_style.py
  src/layman/layer/rest_layer_thumbnail.py
  src/layman/layer/rest_layers.py
  src/layman/map/rest_map.py
  src/layman/map/rest_map_file.py
  src/layman/map/rest_map_metadata_comparison.py
  src/layman/map/rest_map_thumbnail.py
  src/layman/map/rest_maps.py
  src/layman/map/rest_maps_authz_test.py
  src/layman/map/rest_test.py
  src/layman/map/util.py
  src/layman/user/rest_current_user.py
  src/layman/user/rest_users.py
  src/layman/util.py
  src/layman_settings.py
  test/process.py
Labels: enhancement
